id: P000627
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:53:17.924155
source_metadata:
  id: bdr:W25092
  title: ཁམས་སྲིང་མོ་རྫོང་གི་གནས་ཡིག་དཀར་ཆག
  author: ''
  volumes:
    d0f47fe2e3164a999d2855777ee4b5f9:
      image_group_id: I1KG18517
      title: ''
      volume_number: 1
      total_pages: 110
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
