id: I1FF92220
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:33:38+00:00'
last_modified: '2022-06-07T12:30:08.120551+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25092
  title: ཁམས་སྲིང་མོ་རྫོང་གི་གནས་ཡིག་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4620':
      image_group_id: I1KG18517
      title: ''
      total_pages: 110
      order: 1
      base_file: 4620.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
